
services:
  nestproject:
    container_name: 'push-notification'
    restart: always
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./src/DockerFile
    ports:
      - '2020:2020'
    volumes:
      - .:/home/node/app
    links:
      - db
    depends_on:
      - db
    networks:
      - backend

  db:
    image: mysql
    container_name: push-notification-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: push-notification
    volumes:
      - push-notification-project-mysql:/var/lib/mysql
    ports:
      - 3310:3306
    networks:
      - backend

  phpmyadmin:
    platform: linux/x86_64
    restart: always
    container_name: 'phpmyadmin-push-tfcoi'
    image: phpmyadmin/phpmyadmin
    env_file:
      - ./.env
    links:
      - db:db
    ports:
      - '8010:80'
    environment:
      MYSQL_USERNAME: 'root'
      MYSQL_ROOT_PASSWORD: 'test123'
      PMA_HOST: db
    networks:
      - backend

volumes:
  push-notification-project-mysql:
    driver: local

networks:
  backend:
    driver: bridge
